### ISSUE TITLE
AWS S3 storage 403 Forbidden error

### ISSUE THREAD

**Issue by icreatestuff** [spacecatninja/craft-imager-x#31]
### I'm submitting a... 
- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
1. Setup AWS storage option in `imager-x.php` config
2. Load a page using craft.image.transformImage method e.g.
```twig
{% set transformedImages = craft.imager.transformImage(image, [
        { width: 800 },
        { width: 400 }
    ],
    {
        ratio: 16/9
    })
%}
```

### Description
With the Craft debug bar enabled I can see that AWS throws a 403 forbidden error when imager is trying to upload the transformed version to the S3 Bucket. The image source is itself the same S3 bucket setup as a Craft volume from which I can upload and retrieve/show images using the native Craft asset model.

### Displayed errors, stack trace, relevant logs  
Error from Craft debug bar

**Category**
```
spacecatninja\imagerx\externalstorage\AwsStorage::upload
```
**Message**
```
An error occured while uploading to Amazon S3: Error executing "PutObject" on "https://mybucket.s3.eu-west-2.amazonaws.com/transforms/images/9/image-test.jpg"; 
AWS HTTP error: Client error: `PUT https://mybucket.s3.eu-west-2.amazonaws.com/transforms/images/9/image-test.jpg` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>69A35F (truncated...)
    AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
    <Error>
        <Code>AccessDenied</Code>
        <Message>Access Denied</Message>
        <RequestId>69A35F1C0EFRED7F</RequestId>
<HostId>+BT+v5sNMAHrPKwRw7uW2L9jc1vypiEWBjFlbwCDxHYYI8XYi/qhvrFvsMLhFIrDCX3S8dl4GRk=</HostId>
    </Error>
```

I can see that within the webroot imager directory the transformed images are created, then almost immediately deleted as they can't be copied up to S3.

My `imager-x.php` config files is as follows:

```php
<?php
return [
    'imagerUrl' => getenv('CLOUDFRONT_URL'),
    'storages' => ['aws'],
    'storageConfig' => [
        'aws'  => [
            'accessKey' => getenv('S3_KEY_ID'),
            'secretAccessKey' => getenv('S3_SECRET'),
            'region' => getenv('S3_REGION'),
            'bucket' => getenv('S3_BUCKET'),
            'folder' => 'transforms',
            'requestHeaders' => array(),
            'storageType' => 'standard',
            'cloudfrontInvalidateEnabled' => true,
            'cloudfrontDistributionId' => getenv('CLOUDFRONT_DISTRIBUTION_ID'),
        ],
    ]
];
```

Am I doing anything incorrectly here?
Many thanks,
Matt

### Additional info

- Imager version & edition: 3.0.10
- Imager transformer: Craft
- Craft version: 3.4.23
- PHP version: 7.4.2
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.9.6-2)
- Database driver & version: MySQL 5.7.26

**Comment by aelvan** [comment]
Hi Matt,

Everything looks correct, so there probably is an error in the credentials/permissions somewhere. 

Are you using the same env-variables in Craft too? Could you try just adding the values directly to the config file, just to make sure that there's not some issue where the env variables isn't being read. And double check that there isn't a mixup in what values are stored in which variables (ie a mix up of secret and key). 

How have you set up the permissions on the bucket?

**Comment by icreatestuff** [comment]
Hey André,

Thanks for getting back to me. 

It's using exactly the same environment variables in the Craft volume, and that's working.

I followed this guide to get the S3 bucket, Cloudfront and the permissions setup (https://nystudio107.com/blog/using-aws-s3-buckets-cloudfront-distribution-with-craft-cms). Perhaps there's something in here which is incompatible with the way imager-x is trying to do the upload to S3?

I've just swapped out the ENV variables for the values themselves but the same errors occur so the env variables seem to be working correctly.

Many thanks,
Matt

**Comment by aelvan** [comment]
Just tested with a bucket I previously set up, and it's still working. But let me have a go at setting up a new one the way the blog post suggests. Your bucket is in region eu-west-2?

**Comment by icreatestuff** [comment]
Yes eu-west-2. Thanks!

**Comment by aelvan** [comment]
Ok, I can confirm that with that setup I also see the same error. I'll try to come up with a fix shortly!

**Comment by aelvan** [comment]
So, it turns out that the issue was that I was always trying to set public-read on the object that was uploaded to S3. With the policy from Andrew's blog post, that wasn't allowed. 

I've fixed this in v3.0.11 by adding a new config setting to the AWS settings, you can now set `'public' => false`, to have the ACL set to `'private'` (see the [updated docs](https://imager-x.spacecat.ninja/configuration.html#storageconfig-array)). This should let you upload the transforms to the bucket - let me know if that works for you.

However, as I experienced while testing this, sometimes Cloudfront will (307) redirect you to the S3 URL for various reasons ([see this SE thread](https://stackoverflow.com/a/45047048/937388)), in which case the file will not be accessible at all. So, I'm not 100% sure if I'd go down this route myself.

**Comment by icreatestuff** [comment]
Thanks for working up a fix so quickly! Seems to be working fine so far, I’ve not had any 307 redirects as yet.

Matt

**Comment by aelvan** [comment]
Cool. I got that right after setting up the distribution, but now it's working. So maybe it's just until the CDN propagates.

**Comment by johnj24** [comment]
Sorry to add to a closed issue, but I'm having the same issue. I too followed Andrew's blog post about setting up S3 and CloudFront. I've added `'public' => false` to the config as mentioned above. Still getting a 403 in the console on the transformed image. For what it's worth, I can see the source image fine when going to it its link in the assets control panel. 

Here's my config:

```
<?php

use craft\helpers\App;

return [
  'useForCpThumbs' => true,
  'imagerUrl' => App::env('CLOUDFRONT_URL'),
  'storages' => ['aws'],
  'storageConfig' => [
    'aws'  => [
      'accessKey' => App::env('S3_ACCESS_KEY'),
      'secretAccessKey' => App::env('S3_SECRET_KEY'),
      'region' => App::env('S3_REGION'),
      'bucket' => App::env('S3_BUCKET'),
      'folder' => 'transforms',
      'requestHeaders' => array(),
      'storageType' => 'standard',
      'public' => false,
      'cloudfrontInvalidateEnabled' => true,
      'cloudfrontDistributionId' => App::env('CLOUDFRONT_DISTRIBUTION_ID'),
    ],
  ]
];
```

**Additional Information**
Imager version: 3.4
Craft version: 3.6.17
Image driver & version: GD 7.4.9

**Comment by aelvan** [comment]
Hi @johnj24,

Not able to test this right now, but will reopen and test as soon as possible. Can you post the error message you're seeing in the debug bar? And what region is your bucket in?

**Comment by johnj24** [comment]
@aelvan My apologies, I ended up deleting my original message. Not even 2 minutes after I posted, I was able to fix the issue. I messed with the config some more and added a folder to `imagerUrl` to match the S3 folder and voila, it worked!

Here is it for reference:
```
'imagerUrl' => App::env('CLOUDFRONT_URL') . '/transforms/',
```

**Comment by iamtompickering** [comment]
Alongside following the instructions on https://nystudio107.com/blog/using-aws-s3-buckets-cloudfront-distribution-with-craft-cms I had to go through a number of the steps listed here  https://stackoverflow.com/questions/71080354/getting-the-bucket-does-not-allow-acls-error

Hopefully helps anyone else out if they are having issues with this error still.
